### ISSUE TITLE
lambda-formation.util clashed with stdlib.util

### ISSUE THREAD

**Issue by estahn** [SungardAS/lambda-formation#7]
var util = require('lambda-formation').util;

https://nodejs.org/api/util.html

**Comment by kmcgrath** [comment]
I realize this was probably an unfortunate pick of names, but how did the clash happen?  Both would have be set to the same object in the same module.  Did this happen to you?

quick work around would be:
```
var lfUtil = require("lambda-formation").util;
var nodeUtil = require("util");
// or
var util = require("util");
```

**Comment by estahn** [comment]
@kmcgrath I did change the assignment like you suggested.
