### ISSUE TITLE
Invalid Response object: Value of property Reason must be of type String

### ISSUE THREAD

**Issue by estahn** [SungardAS/lambda-formation#8]
https://github.com/SungardAS/lambda-formation/blob/master/lib/util/done.js#L19

This needs to be converted to a string as `err` is an object.

```js
route53.changeTagsForResource(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Route53.html#createHostedZone-property

**Comment by estahn** [comment]
I changed it to `.Reason = JSON.stringify(err)`

**Comment by kmcgrath** [comment]
New process will check if `err` is a string, then if it is an object with a `message` key (like Error objects) and lastly use `JSON.stringify`

**Comment by estahn** [comment]
@kmcgrath Great, thanks for the quick turn-around.
