### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by estahn** [SungardAS/lambda-formation#9]
This is a feature request to add logging out of the box.

- [x] Easy declaration such as `var log = require('lambda-formation').logger;`
- [x] `projectHandler` and `resourceHandler` should always log arguments with log-level `debug`
- [x] Ability to set/enable/disable log-level via environment variables
- [x] Add documentation

**Comment by estahn** [comment]
@kmcgrath See #10

**Comment by estahn** [comment]
@kmcgrath Did you have a chance to look at the pull requests?

**Comment by kmcgrath** [comment]
@estahn thank you for the requests. I have seen them, but won't be able to give them a good look until tomorrow or Saturday.

They are in my queue ;)

**Comment by kmcgrath** [comment]
I like this idea.

Implemented something similar in [spotinst-lambda](https://github.com/SungardAS/spotinst-lambda/blob/master/lib/log.js)

At the time the decision was to push logs to downstream projects to keep lambda-formation as light as possible.  With that said, logs are a very fundamental thing that should probably be supported by the framework.

Running short on time tonight, but will come back to this tomorrow.  Just want to compare what we did before and this.

**Comment by estahn** [comment]
Yes, I think I copied the winston part from `cfn-responder`. The only bit I dislike is the use of `process.env.CFN_LOG_LEVEL` directly in `lib/logger/index.js`. 

It might be a better idea to do something with a config object, e.g.

```js
var LambdaFormation = require('lambda-formation');

LambdaFormation.config.log_level = process.env.CFN_LOG_LEVEL;
```
And use this in `lib/logger/index.js`.

**Comment by kmcgrath** [comment]
Thanks again for the submission! #10 has been merged.
